name: digitalocean_docker_streamlit
services:
- dockerfile_path: Dockerfile
  github:
    branch: main
    deploy_on_push: true
    repo: weberon/digitalocean_docker_streamlit
  name: digitalocean_docker_streamlit
